name = "ProductionPlanningProblems"
uuid = "1ac99db7-4a60-487e-b13d-9b5f203d1adf"
authors = ["Rafael Martinelli <martinelli@puc-rio.br>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"
